//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class comments
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        [DisplayName("Tarih")]
        public Nullable<System.DateTime> date { get; set; }
        [DisplayName("Onay")]
        public Nullable<bool> confirmation { get; set; }
        [DisplayName("Ýçerik")]
        public string content { get; set; }
        [DisplayName("Yemek Id")]
        public Nullable<int> meal_id { get; set; }
    
        public virtual recipes recipes { get; set; }
        public virtual users users { get; set; }
    }
}
