//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class websiteEntities6 : DbContext
    {
        public websiteEntities6()
            : base("name=websiteEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<recipes> recipes { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<VoteLog> VoteLog { get; set; }
    }
}
