//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class recipes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recipes()
        {
            this.comments = new HashSet<comments>();
        }
    
        public int id { get; set; }
        [DisplayName("Ad")]
        public string name { get; set; }
        [DisplayName("Malzemeler")]
        public string material { get; set; }
        [DisplayName("Hazýrlanýþ")]
        public string preparation { get; set; }
        [DisplayName("Resim")]
        public string image { get; set; }
        [DisplayName("Tarih")]
        public Nullable<System.DateTime> date { get; set; }
        [DisplayName("Kategori Adý")]
        public Nullable<int> categori_id { get; set; }
        [DisplayName("Kullanýcý Adý")]
        public Nullable<int> user_id { get; set; }
        [DisplayName("Oy")]
        public string Vote { get; set; }
    
        public virtual categories categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
        public virtual users users { get; set; }
    }
}
