//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public users()
        {
            this.comments = new HashSet<comments>();
            this.recipes = new HashSet<recipes>();
        }
    
        public int id { get; set; }
        [DisplayName("Ad Soyad")]
        public string name_sname { get; set; }
        [DisplayName("Mail Adresi")]
        public string mail { get; set; }
        [DisplayName("Þifre")]
        public string password { get; set; }
        [DisplayName("Cinsiyet")]
        public Nullable<bool> gender { get; set; }
        [DisplayName("Resim")]
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recipes> recipes { get; set; }
    }
}
