//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoteLog
    {
        public int AutoId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> VoteForId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> Vote { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
